// This file is auto-generated by @hey-api/openapi-ts

export const $GetUserByGuidResponse = {
    type: 'object',
    properties: {
        user: {
            '$ref': '#/components/schemas/User'
        }
    },
    additionalProperties: false
} as const;

export const $User = {
    type: 'object',
    properties: {
        guid: {
            type: 'string',
            format: 'uuid'
        },
        phoneNumber: {
            type: 'string',
            nullable: true
        },
        firstName: {
            type: 'string',
            nullable: true
        },
        lastName: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            nullable: true
        },
        avatar: {
            type: 'string',
            nullable: true
        },
        passwordHash: {
            type: 'string',
            nullable: true
        },
        isActive: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;