/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WithButtonAppBarImport } from './routes/_with-ButtonAppBar'
import { Route as IndexImport } from './routes/index'
import { Route as RegistrationIndexImport } from './routes/Registration/index'
import { Route as LoginIndexImport } from './routes/Login/index'
import { Route as RegistrationRegistrationFormImport } from './routes/Registration/RegistrationForm'
import { Route as LoginLoginPageImport } from './routes/Login/LoginPage'
import { Route as LoginLoginFormImport } from './routes/Login/LoginForm'
import { Route as WithButtonAppBarDashboardIndexImport } from './routes/_with-ButtonAppBar/Dashboard/index'
import { Route as WithButtonAppBarDashboardUsersTableImport } from './routes/_with-ButtonAppBar/Dashboard/UsersTable'
import { Route as WithButtonAppBarDashboardTicketsTableImport } from './routes/_with-ButtonAppBar/Dashboard/TicketsTable'
import { Route as WithButtonAppBarDashboardAnalyticsImport } from './routes/_with-ButtonAppBar/Dashboard/Analytics'

// Create/Update Routes

const WithButtonAppBarRoute = WithButtonAppBarImport.update({
  id: '/_with-ButtonAppBar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegistrationIndexRoute = RegistrationIndexImport.update({
  path: '/Registration/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/Login/',
  getParentRoute: () => rootRoute,
} as any)

const RegistrationRegistrationFormRoute =
  RegistrationRegistrationFormImport.update({
    path: '/Registration/RegistrationForm',
    getParentRoute: () => rootRoute,
  } as any)

const LoginLoginPageRoute = LoginLoginPageImport.update({
  path: '/Login/LoginPage',
  getParentRoute: () => rootRoute,
} as any)

const LoginLoginFormRoute = LoginLoginFormImport.update({
  path: '/Login/LoginForm',
  getParentRoute: () => rootRoute,
} as any)

const WithButtonAppBarDashboardIndexRoute =
  WithButtonAppBarDashboardIndexImport.update({
    path: '/Dashboard/',
    getParentRoute: () => WithButtonAppBarRoute,
  } as any)

const WithButtonAppBarDashboardUsersTableRoute =
  WithButtonAppBarDashboardUsersTableImport.update({
    path: '/Dashboard/UsersTable',
    getParentRoute: () => WithButtonAppBarRoute,
  } as any)

const WithButtonAppBarDashboardTicketsTableRoute =
  WithButtonAppBarDashboardTicketsTableImport.update({
    path: '/Dashboard/TicketsTable',
    getParentRoute: () => WithButtonAppBarRoute,
  } as any)

const WithButtonAppBarDashboardAnalyticsRoute =
  WithButtonAppBarDashboardAnalyticsImport.update({
    path: '/Dashboard/Analytics',
    getParentRoute: () => WithButtonAppBarRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_with-ButtonAppBar': {
      id: '/_with-ButtonAppBar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithButtonAppBarImport
      parentRoute: typeof rootRoute
    }
    '/Login/LoginForm': {
      id: '/Login/LoginForm'
      path: '/Login/LoginForm'
      fullPath: '/Login/LoginForm'
      preLoaderRoute: typeof LoginLoginFormImport
      parentRoute: typeof rootRoute
    }
    '/Login/LoginPage': {
      id: '/Login/LoginPage'
      path: '/Login/LoginPage'
      fullPath: '/Login/LoginPage'
      preLoaderRoute: typeof LoginLoginPageImport
      parentRoute: typeof rootRoute
    }
    '/Registration/RegistrationForm': {
      id: '/Registration/RegistrationForm'
      path: '/Registration/RegistrationForm'
      fullPath: '/Registration/RegistrationForm'
      preLoaderRoute: typeof RegistrationRegistrationFormImport
      parentRoute: typeof rootRoute
    }
    '/Login/': {
      id: '/Login/'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/Registration/': {
      id: '/Registration/'
      path: '/Registration'
      fullPath: '/Registration'
      preLoaderRoute: typeof RegistrationIndexImport
      parentRoute: typeof rootRoute
    }
    '/_with-ButtonAppBar/Dashboard/Analytics': {
      id: '/_with-ButtonAppBar/Dashboard/Analytics'
      path: '/Dashboard/Analytics'
      fullPath: '/Dashboard/Analytics'
      preLoaderRoute: typeof WithButtonAppBarDashboardAnalyticsImport
      parentRoute: typeof WithButtonAppBarImport
    }
    '/_with-ButtonAppBar/Dashboard/TicketsTable': {
      id: '/_with-ButtonAppBar/Dashboard/TicketsTable'
      path: '/Dashboard/TicketsTable'
      fullPath: '/Dashboard/TicketsTable'
      preLoaderRoute: typeof WithButtonAppBarDashboardTicketsTableImport
      parentRoute: typeof WithButtonAppBarImport
    }
    '/_with-ButtonAppBar/Dashboard/UsersTable': {
      id: '/_with-ButtonAppBar/Dashboard/UsersTable'
      path: '/Dashboard/UsersTable'
      fullPath: '/Dashboard/UsersTable'
      preLoaderRoute: typeof WithButtonAppBarDashboardUsersTableImport
      parentRoute: typeof WithButtonAppBarImport
    }
    '/_with-ButtonAppBar/Dashboard/': {
      id: '/_with-ButtonAppBar/Dashboard/'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof WithButtonAppBarDashboardIndexImport
      parentRoute: typeof WithButtonAppBarImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  WithButtonAppBarRoute: WithButtonAppBarRoute.addChildren({
    WithButtonAppBarDashboardAnalyticsRoute,
    WithButtonAppBarDashboardTicketsTableRoute,
    WithButtonAppBarDashboardUsersTableRoute,
    WithButtonAppBarDashboardIndexRoute,
  }),
  LoginLoginFormRoute,
  LoginLoginPageRoute,
  RegistrationRegistrationFormRoute,
  LoginIndexRoute,
  RegistrationIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_with-ButtonAppBar",
        "/Login/LoginForm",
        "/Login/LoginPage",
        "/Registration/RegistrationForm",
        "/Login/",
        "/Registration/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_with-ButtonAppBar": {
      "filePath": "_with-ButtonAppBar.tsx",
      "children": [
        "/_with-ButtonAppBar/Dashboard/Analytics",
        "/_with-ButtonAppBar/Dashboard/TicketsTable",
        "/_with-ButtonAppBar/Dashboard/UsersTable",
        "/_with-ButtonAppBar/Dashboard/"
      ]
    },
    "/Login/LoginForm": {
      "filePath": "Login/LoginForm.tsx"
    },
    "/Login/LoginPage": {
      "filePath": "Login/LoginPage.tsx"
    },
    "/Registration/RegistrationForm": {
      "filePath": "Registration/RegistrationForm.tsx"
    },
    "/Login/": {
      "filePath": "Login/index.tsx"
    },
    "/Registration/": {
      "filePath": "Registration/index.tsx"
    },
    "/_with-ButtonAppBar/Dashboard/Analytics": {
      "filePath": "_with-ButtonAppBar/Dashboard/Analytics.tsx",
      "parent": "/_with-ButtonAppBar"
    },
    "/_with-ButtonAppBar/Dashboard/TicketsTable": {
      "filePath": "_with-ButtonAppBar/Dashboard/TicketsTable.tsx",
      "parent": "/_with-ButtonAppBar"
    },
    "/_with-ButtonAppBar/Dashboard/UsersTable": {
      "filePath": "_with-ButtonAppBar/Dashboard/UsersTable.tsx",
      "parent": "/_with-ButtonAppBar"
    },
    "/_with-ButtonAppBar/Dashboard/": {
      "filePath": "_with-ButtonAppBar/Dashboard/index.tsx",
      "parent": "/_with-ButtonAppBar"
    }
  }
}
ROUTE_MANIFEST_END */
